site_name:        HoTRG_lemon.jl
repo_url:         https://github.com/yoyoyoju/HoTRG_lemon.jl
site_description: hotrg for fractal lattice
site_author:      yoyoyoju

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
  - Home: index.md
